#include "Grammar.h"

#include <algorithm>
#include <cstdlib>
#include <stdexcept>

#include "antlr4-runtime.h"
#include "generated/support/Keywords.h"

namespace tsql::editor::detail {

// One per built grammar (EditorGrammar.cpp.in); the list is generated by CMake.
#define TSQL_GRAMMAR(G, V) const Grammar& EditorGrammar##G();
#include "tsql_parser_grammars.inc"
#undef TSQL_GRAMMAR

const Grammar& GrammarFor(SqlVersion version) {
#define TSQL_GRAMMAR(G, V) \
    if (version == SqlVersion::V) return EditorGrammar##G();
#include "tsql_parser_grammars.inc"
#undef TSQL_GRAMMAR
    const char* name = GrammarName(version);
    throw std::invalid_argument(std::string("tsql::editor: no parser for ") +
                                (name ? std::string(name) + " in this build (TSQL_PARSER_GRAMMARS)"
                                      : "SqlVersion " + std::to_string(static_cast<int>(version))));
}

namespace {

/// The number of tokens from the token matched at `from` to the token matched at `to` when every
/// path between them in their rule has the same number (0: not fixed or `to` unreachable).
size_t FixedDistance(const antlr4::atn::ATN& atn, size_t from, size_t to) {
    using antlr4::atn::TransitionType;
    constexpr int kUnknown = -1, kMax = 16;
    const antlr4::atn::ATNState* start = atn.states[from];
    // a token match state has exactly one token transition
    if (start->transitions.size() != 1 || start->transitions[0]->isEpsilon()) return 0;
    std::vector<std::pair<const antlr4::atn::ATNState*, int>> work = {{start->transitions[0]->target, 1}};
    std::vector<std::pair<size_t, int>> seen;
    int found = 0;   // 0: none yet
    while (!work.empty()) {
        auto [s, n] = work.back();
        work.pop_back();
        if (n > kMax) n = kUnknown;
        const std::pair<size_t, int> key(s->stateNumber, n);
        if (std::find(seen.begin(), seen.end(), key) != seen.end()) continue;
        seen.push_back(key);
        if (s->stateNumber == to) {
            if (n == kUnknown || (found != 0 && found != n)) return 0;
            found = n;
            continue;
        }
        if (s->getStateType() == antlr4::atn::ATNStateType::RULE_STOP) continue;   // left the rule
        for (const auto& tp : s->transitions) {
            const antlr4::atn::Transition* t = tp.get();
            switch (t->getTransitionType()) {
                case TransitionType::RULE:   // a rule's length is not fixed: continue after it, unknown
                    work.emplace_back(static_cast<const antlr4::atn::RuleTransition*>(t)->followState, kUnknown);
                    break;
                case TransitionType::EPSILON:
                case TransitionType::ACTION:
                case TransitionType::PREDICATE:
                case TransitionType::PRECEDENCE:
                    work.emplace_back(t->target, n);
                    break;
                default:
                    work.emplace_back(t->target, n == kUnknown ? kUnknown : n + 1);
                    break;
            }
        }
    }
    return found > 0 ? static_cast<size_t>(found) : 0;
}

}  // namespace

void Grammar::Init(SqlVersion v, int flag, antlr4::Parser& parser, const KeywordStateEntry* states, size_t nStates,
                   const KeywordGuardEntry* guards, const PredicateEntry* preds, size_t nPreds,
                   const RuleActionsEntry* actions, const ReturningActionEntry* returning, const int* predicted) {
    version = v;
    versionFlag = flag;
    atn = &parser.getATN();
    ruleNames = &parser.getRuleNames();
    vocabulary = &parser.getVocabulary();
    for (size_t i = 0; i < nStates; ++i) {
        if ((states[i].versionMask & versionFlag) == 0) continue;
        KeywordState& ks = keywordStates[states[i].state];
        ks.words.emplace_back(states[i].word);
        ks.binding = ks.binding || states[i].binding;
    }
    for (auto& [state, ks] : keywordStates) {
        std::sort(ks.words.begin(), ks.words.end());
        ks.words.erase(std::unique(ks.words.begin(), ks.words.end()), ks.words.end());
    }
    // guards, grouped by (state, guard state) in table order
    for (const KeywordGuardEntry* e = guards; e->state >= 0;) {
        const KeywordGuardEntry* first = e;
        KeywordGuard guard;
        for (; e->state == first->state && e->guardState == first->guardState; ++e)
            if ((e->versionMask & versionFlag) != 0) guard.words.emplace_back(e->word);
        guard.distance = FixedDistance(*atn, static_cast<size_t>(first->guardState), static_cast<size_t>(first->state));
        if (guard.distance == 0 || guard.words.empty()) continue;
        std::sort(guard.words.begin(), guard.words.end());
        keywordGuards[first->state].push_back(std::move(guard));
    }
    for (size_t i = 0; i < nPreds; ++i) predicates.emplace(static_cast<size_t>(preds[i].index), preds[i].expr);
    for (size_t t = 0; t <= vocabulary->getMaxTokenType(); ++t) {
        const std::string name(vocabulary->getSymbolicName(t));
        if (!name.empty()) tokenTypes.emplace(name, t);
    }
    for (const char* name : {"statement", "lastStatement"}) {
        const size_t r = RuleIndex(name);
        if (r != SIZE_MAX) statementRules.push_back(r);
    }
    // each rule's ACTION transitions in state order are its actions in text order (the ATN builder
    // numbers elements and actions as it meets them)
    std::vector<std::vector<size_t>> ruleActions(ruleNames->size());
    for (const antlr4::atn::ATNState* s : atn->states)   // (in state order)
        if (s != nullptr && !s->transitions.empty() &&
            s->transitions[0]->getTransitionType() == antlr4::atn::TransitionType::ACTION)
            ruleActions[s->ruleIndex].push_back(s->stateNumber);
    rejectingAction.assign(atn->states.size(), 0);
    std::vector<uint8_t> mismatched(ruleNames->size(), 0);
    for (const RuleActionsEntry* e = actions; e->rule != nullptr; ++e) {
        const size_t rule = RuleIndex(e->rule);
        if (rule == SIZE_MAX) continue;
        const std::vector<size_t>& at = ruleActions[rule];
        if (at.size() != static_cast<size_t>(e->count)) {
            ++actionTableMismatches;
            mismatched[rule] = 1;
            for (size_t s : at) rejectingAction[s] = 1;
            continue;
        }
        for (const char* p = e->rejecting; *p != '\0';) {
            char* end = nullptr;
            const unsigned long k = std::strtoul(p, &end, 10);
            if (end == p) break;
            if (k < at.size()) rejectingAction[at[k]] = 1;
            p = end;
        }
    }
    for (const ReturningActionEntry* e = returning; e->rule != nullptr; ++e) {
        const size_t rule = RuleIndex(e->rule);
        if (rule == SIZE_MAX || mismatched[rule] || static_cast<size_t>(e->ordinal) >= ruleActions[rule].size()) continue;
        returningAction.emplace(ruleActions[rule][static_cast<size_t>(e->ordinal)], e->condition);
    }
    predictedDecision.assign(atn->states.size(), 0);
    for (const int* d = predicted; *d >= 0; ++d)
        if (static_cast<size_t>(*d) < atn->decisionToState.size())
            predictedDecision[atn->decisionToState[static_cast<size_t>(*d)]->stateNumber] = 1;
    InitTopLevel();
    InitActionAhead();
}

void Grammar::InitActionAhead() {
    using antlr4::atn::TransitionType;
    const std::vector<antlr4::atn::ATNState*>& states = atn->states;
    actionAhead.assign(states.size(), 0);
    for (const antlr4::atn::ATNState* s : states)
        if (s != nullptr && s->getStateType() == antlr4::atn::ATNStateType::RULE_STOP) actionAhead[s->stateNumber] = kEndAhead;
    // a fixpoint over the transitions that take no token (a rule stop's transitions lead to every
    // caller: what follows a rule's end is the walk's business, by its rule calls), up to where the
    // parser looks at the next token: a decision (inline or predicted; sync's test of a (...)?
    // block) or a returning action's test. What runs after that runs with the next token there, and
    // a trial parse (TryParse) whose text ends there stops at it or decides by the end.
    for (bool changed = true; changed;) {
        changed = false;
        for (auto it = states.rbegin(); it != states.rend(); ++it) {
            const antlr4::atn::ATNState* s = *it;
            if (s == nullptr || s->getStateType() == antlr4::atn::ATNStateType::RULE_STOP) continue;
            if (antlr4::atn::DecisionState::is(s) && s->transitions.size() > 1) continue;
            uint8_t ahead = actionAhead[s->stateNumber];
            for (const auto& tp : s->transitions) {
                const antlr4::atn::Transition* t = tp.get();
                switch (t->getTransitionType()) {
                    case TransitionType::RULE: {
                        const auto* rt = static_cast<const antlr4::atn::RuleTransition*>(t);
                        const uint8_t callee = actionAhead[rt->target->stateNumber];
                        ahead |= callee & kRejectAhead;
                        if (callee & kEndAhead) ahead |= actionAhead[rt->followState->stateNumber];
                        break;
                    }
                    case TransitionType::ACTION:
                        if (rejectingAction[s->stateNumber] != 0) ahead |= kRejectAhead;
                        if (returningAction.count(s->stateNumber) == 0) ahead |= actionAhead[t->target->stateNumber];
                        break;
                    case TransitionType::EPSILON:
                    case TransitionType::PREDICATE:
                    case TransitionType::PRECEDENCE:
                        ahead |= actionAhead[t->target->stateNumber];
                        break;
                    default:   // takes a token
                        break;
                }
            }
            if (ahead != actionAhead[s->stateNumber]) {
                actionAhead[s->stateNumber] = ahead;
                changed = true;
            }
        }
    }
}

namespace {

using antlr4::atn::ATNState;
using antlr4::atn::TransitionType;

/// The state of rule `rule` from which a RULE transition calls `callee` and that `accept`s.
template <class Accept>
size_t FindCall(const antlr4::atn::ATN& atn, size_t rule, size_t callee, const Accept& accept) {
    for (const ATNState* s : atn.states) {
        if (s == nullptr || s->ruleIndex != rule) continue;
        for (const auto& t : s->transitions)
            if (t->getTransitionType() == TransitionType::RULE &&
                static_cast<const antlr4::atn::RuleTransition*>(t.get())->ruleIndex == callee && accept(s))
                return s->stateNumber;
    }
    throw std::logic_error("tsql::editor: unexpected script/batch rule shape");
}

/// Whether `to` is reachable from `from` over epsilon transitions within the rule.
bool EpsilonReaches(const ATNState* from, const ATNState* to) {
    std::vector<const ATNState*> work{from};
    std::vector<size_t> seen;
    while (!work.empty()) {
        const ATNState* s = work.back();
        work.pop_back();
        if (s == to) return true;
        if (std::find(seen.begin(), seen.end(), s->stateNumber) != seen.end()) continue;
        seen.push_back(s->stateNumber);
        for (const auto& t : s->transitions)
            if (t->isEpsilon() && t->getTransitionType() != TransitionType::RULE) work.push_back(t->target);
    }
    return false;
}

}  // namespace

void Grammar::InitTopLevel() {
    TopLevelStates& t = top;
    t.scriptRule = RuleIndex("script");
    t.batchRule = RuleIndex("batch");
    t.statementOptSemiRule = RuleIndex("statementOptSemi");
    if (t.scriptRule == SIZE_MAX || t.batchRule == SIZE_MAX || t.statementOptSemiRule == SIZE_MAX)
        throw std::logic_error("tsql::editor: grammar without script/batch/statementOptSemi");
    const size_t go = tokenTypes.at("Go");
    for (const ATNState* s : atn->states) {
        if (s == nullptr || s->ruleIndex != t.scriptRule) continue;
        for (const auto& tr : s->transitions) {
            if (tr->getTransitionType() != TransitionType::ATOM) continue;
            const size_t label = static_cast<const antlr4::atn::AtomTransition*>(tr.get())->_label;
            if (label == go) t.scriptGo = s->stateNumber;
            if (label == antlr4::Token::EOF) t.scriptEof = s->stateNumber;
        }
        if (s->getStateType() == antlr4::atn::ATNStateType::STAR_LOOP_ENTRY)
            t.scriptLoopBack = static_cast<const antlr4::atn::StarLoopEntryState*>(s)->loopBackState->stateNumber;
    }
    const ATNState* afterGo = atn->states[t.scriptGo]->transitions[0]->target;
    t.scriptLoopBatchCall =
        FindCall(*atn, t.scriptRule, t.batchRule, [&](const ATNState* s) { return EpsilonReaches(afterGo, s); });
    t.scriptFirstBatchCall =
        FindCall(*atn, t.scriptRule, t.batchRule, [&](const ATNState* s) { return !EpsilonReaches(afterGo, s); });
    t.batchStatementCall = FindCall(*atn, t.batchRule, t.statementOptSemiRule, [](const ATNState*) { return true; });
    const ATNState* call = atn->states[t.batchStatementCall];
    for (const ATNState* s : atn->states) {
        if (s == nullptr || s->ruleIndex != t.batchRule || s->getStateType() != antlr4::atn::ATNStateType::STAR_LOOP_ENTRY)
            continue;
        const auto* entry = static_cast<const antlr4::atn::StarLoopEntryState*>(s);
        // the loop's body branch (alternative 1) leads to the call
        if (!EpsilonReaches(entry->transitions[0]->target, call)) continue;
        t.batchLoopBack = entry->loopBackState->stateNumber;
        t.batchLoopDecision = static_cast<size_t>(entry->decision);
    }
    if (t.batchLoopBack == 0) throw std::logic_error("tsql::editor: unexpected batch rule shape");
}

bool Grammar::OpaquePredicate(size_t predIndex) const {
    auto it = predicates.find(predIndex);
    return it == predicates.end() || it->second.find_first_of("?$") != std::string::npos;
}

void Grammar::Lex(std::string_view sql, std::vector<LexToken>& out) const {
    out.clear();
    LexFrom(sql, 0, true, [&](const LexedToken& t) {
        out.push_back(t.token);
        return true;
    });
}

size_t Grammar::RuleIndex(std::string_view name) const {
    for (size_t i = 0; i < ruleNames->size(); ++i)
        if ((*ruleNames)[i] == name) return i;
    return SIZE_MAX;
}

bool Grammar::StateMatches(int state, uint32_t type) const {
    if (state < 0 || static_cast<size_t>(state) >= atn->states.size()) return false;
    for (const auto& t : atn->states[static_cast<size_t>(state)]->transitions)
        if (t->matches(type, antlr4::Token::MIN_USER_TOKEN_TYPE, atn->maxTokenType)) return true;
    return false;
}

bool IsHiddenType(uint32_t type) {
    using T = ast::TSqlTokenType;
    return type == static_cast<uint32_t>(T::WhiteSpace) || type == static_cast<uint32_t>(T::SingleLineComment) ||
           type == static_cast<uint32_t>(T::MultilineComment);
}

namespace {

/// Length of the valid UTF-8 sequence at s[i], or 0 (tsql::detail::Decode's rules: a valid
/// sequence is one code point, any other byte is one U+FFFD).
size_t SequenceLength(std::string_view s, size_t i) {
    const unsigned char c = static_cast<unsigned char>(s[i]);
    if (c < 0x80) return 1;
    size_t n;
    char32_t cp;
    if ((c & 0xE0) == 0xC0) { cp = c & 0x1F; n = 1; }
    else if ((c & 0xF0) == 0xE0) { cp = c & 0x0F; n = 2; }
    else if ((c & 0xF8) == 0xF0) { cp = c & 0x07; n = 3; }
    else return 0;
    for (size_t k = 1; k <= n; ++k) {
        if (i + k >= s.size() || (static_cast<unsigned char>(s[i + k]) & 0xC0) != 0x80) return 0;
        cp = (cp << 6) | (static_cast<unsigned char>(s[i + k]) & 0x3F);
    }
    static const char32_t kMin[] = {0, 0x80, 0x800, 0x10000};
    if (cp < kMin[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return 0;
    return n + 1;
}

bool IsAscii(std::string_view s) {
    for (char c : s)
        if (static_cast<unsigned char>(c) >= 0x80) return false;
    return true;
}

}  // namespace

std::vector<uint32_t> CodePointByteOffsets(std::string_view s) {
    std::vector<uint32_t> out;
    if (IsAscii(s)) return out;
    out.reserve(s.size() + 1);
    for (size_t i = 0; i < s.size();) {
        out.push_back(static_cast<uint32_t>(i));
        const size_t n = SequenceLength(s, i);
        i += n == 0 ? 1 : n;
    }
    out.push_back(static_cast<uint32_t>(s.size()));
    return out;
}

bool SanitizeUtf8(std::string_view s, std::string& out) {
    bool changed = false;
    for (size_t i = 0; i < s.size();) {
        const size_t n = SequenceLength(s, i);
        if (n != 0) {
            if (changed) out.append(s.data() + i, n);
            i += n;
            continue;
        }
        if (!changed) {
            out.assign(s.data(), i);
            changed = true;
        }
        out += "\xEF\xBF\xBD";
        ++i;
    }
    return changed;
}

const char* KeywordText(uint32_t type) {
    static const std::vector<const char*> table = [] {
        std::vector<const char*> t;
        for (const auto& e : parser::kKeywords) {
            const size_t i = static_cast<size_t>(e.type);
            if (t.size() <= i) t.resize(i + 1, nullptr);
            t[i] = e.text;
        }
        return t;
    }();
    return type < table.size() ? table[type] : nullptr;
}

}  // namespace tsql::editor::detail
