#include "Grammar.h"

#include <algorithm>
#include <stdexcept>

#include "antlr4-runtime.h"
#include "generated/support/Keywords.h"

namespace tsql::editor::detail {

// One per built grammar (EditorGrammar.cpp.in); the list is generated by CMake.
#define TSQL_GRAMMAR(G, V) const Grammar& EditorGrammar##G();
#include "tsql_parser_grammars.inc"
#undef TSQL_GRAMMAR

const Grammar& GrammarFor(SqlVersion version) {
#define TSQL_GRAMMAR(G, V) \
    if (version == SqlVersion::V) return EditorGrammar##G();
#include "tsql_parser_grammars.inc"
#undef TSQL_GRAMMAR
    const char* name = GrammarName(version);
    throw std::invalid_argument(std::string("tsql::editor: no parser for ") +
                                (name ? std::string(name) + " in this build (TSQL_PARSER_GRAMMARS)"
                                      : "SqlVersion " + std::to_string(static_cast<int>(version))));
}

void Grammar::Init(SqlVersion v, int flag, antlr4::Parser& parser, const KeywordStateEntry* states, size_t nStates,
                   const PredicateEntry* preds, size_t nPreds) {
    version = v;
    versionFlag = flag;
    atn = &parser.getATN();
    ruleNames = &parser.getRuleNames();
    vocabulary = &parser.getVocabulary();
    for (size_t i = 0; i < nStates; ++i) {
        if ((states[i].versionMask & versionFlag) == 0) continue;
        KeywordState& ks = keywordStates[states[i].state];
        ks.words.emplace_back(states[i].word);
        ks.binding = ks.binding || states[i].binding;
    }
    for (auto& [state, ks] : keywordStates) {
        std::sort(ks.words.begin(), ks.words.end());
        ks.words.erase(std::unique(ks.words.begin(), ks.words.end()), ks.words.end());
    }
    for (size_t i = 0; i < nPreds; ++i) predicates.emplace(static_cast<size_t>(preds[i].index), preds[i].expr);
    for (size_t t = 0; t <= vocabulary->getMaxTokenType(); ++t) {
        const std::string name(vocabulary->getSymbolicName(t));
        if (!name.empty()) tokenTypes.emplace(name, t);
    }
    for (const char* name : {"statement", "lastStatement"}) {
        const size_t r = RuleIndex(name);
        if (r != SIZE_MAX) statementRules.push_back(r);
    }
}

size_t Grammar::RuleIndex(std::string_view name) const {
    for (size_t i = 0; i < ruleNames->size(); ++i)
        if ((*ruleNames)[i] == name) return i;
    return SIZE_MAX;
}

bool Grammar::StateMatches(int state, uint32_t type) const {
    if (state < 0 || static_cast<size_t>(state) >= atn->states.size()) return false;
    for (const auto& t : atn->states[static_cast<size_t>(state)]->transitions)
        if (t->matches(type, antlr4::Token::MIN_USER_TOKEN_TYPE, atn->maxTokenType)) return true;
    return false;
}

bool IsHiddenType(uint32_t type) {
    using T = ast::TSqlTokenType;
    return type == static_cast<uint32_t>(T::WhiteSpace) || type == static_cast<uint32_t>(T::SingleLineComment) ||
           type == static_cast<uint32_t>(T::MultilineComment);
}

namespace {

/// Length of the valid UTF-8 sequence at s[i], or 0 (tsql::detail::Decode's rules: a valid
/// sequence is one code point, any other byte is one U+FFFD).
size_t SequenceLength(std::string_view s, size_t i) {
    const unsigned char c = static_cast<unsigned char>(s[i]);
    if (c < 0x80) return 1;
    size_t n;
    char32_t cp;
    if ((c & 0xE0) == 0xC0) { cp = c & 0x1F; n = 1; }
    else if ((c & 0xF0) == 0xE0) { cp = c & 0x0F; n = 2; }
    else if ((c & 0xF8) == 0xF0) { cp = c & 0x07; n = 3; }
    else return 0;
    for (size_t k = 1; k <= n; ++k) {
        if (i + k >= s.size() || (static_cast<unsigned char>(s[i + k]) & 0xC0) != 0x80) return 0;
        cp = (cp << 6) | (static_cast<unsigned char>(s[i + k]) & 0x3F);
    }
    static const char32_t kMin[] = {0, 0x80, 0x800, 0x10000};
    if (cp < kMin[n] || cp > 0x10FFFF || (cp >= 0xD800 && cp <= 0xDFFF)) return 0;
    return n + 1;
}

bool IsAscii(std::string_view s) {
    for (char c : s)
        if (static_cast<unsigned char>(c) >= 0x80) return false;
    return true;
}

}  // namespace

std::vector<uint32_t> CodePointByteOffsets(std::string_view s) {
    std::vector<uint32_t> out;
    if (IsAscii(s)) return out;
    out.reserve(s.size() + 1);
    for (size_t i = 0; i < s.size();) {
        out.push_back(static_cast<uint32_t>(i));
        const size_t n = SequenceLength(s, i);
        i += n == 0 ? 1 : n;
    }
    out.push_back(static_cast<uint32_t>(s.size()));
    return out;
}

bool SanitizeUtf8(std::string_view s, std::string& out) {
    bool changed = false;
    for (size_t i = 0; i < s.size();) {
        const size_t n = SequenceLength(s, i);
        if (n != 0) {
            if (changed) out.append(s.data() + i, n);
            i += n;
            continue;
        }
        if (!changed) {
            out.assign(s.data(), i);
            changed = true;
        }
        out += "\xEF\xBF\xBD";
        ++i;
    }
    return changed;
}

const char* KeywordText(uint32_t type) {
    static const std::vector<const char*> table = [] {
        std::vector<const char*> t;
        for (const auto& e : parser::kKeywords) {
            const size_t i = static_cast<size_t>(e.type);
            if (t.size() <= i) t.resize(i + 1, nullptr);
            t[i] = e.text;
        }
        return t;
    }();
    return type < table.size() ? table[type] : nullptr;
}

}  // namespace tsql::editor::detail
