// Ported from Microsoft SqlScriptDOM (MIT) @ eaf3a6e: SqlScriptDom/ScriptDom/SqlServer/TSqlFragmentVisitor.cs, SqlScriptDom/ScriptDom/SqlServer/TSqlConcreteFragmentVisitor.cs
// The per-class Visit/ExplicitVisit overloads are generated by tools/astgen/astgen.py.
//
// Behaviour per Ast.xml class T (same as the C# generated code):
//   Visit(T*)          if !VisitBaseType(): Visit(static_cast<TSqlFragment*>(node))
//   ExplicitVisit(T*)  if VisitBaseType(): Visit(Base1*), Visit(Base2*), ..., Visit(TSqlFragment*)
//                      (nearest base first); then Visit(T*); then node->AcceptChildren(this)
// TSqlFragmentVisitor visits base types; TSqlConcreteFragmentVisitor does not, and seals the
// abstract classes' Visit/ExplicitVisit.
//
// C++ note: overriding one Visit/ExplicitVisit overload in a subclass hides the others in that
// subclass's scope (virtual dispatch through Accept is unaffected). Add
// `using TSqlFragmentVisitor::Visit; using TSqlFragmentVisitor::ExplicitVisit;` if the subclass
// itself calls overloads it does not override.
#pragma once

#include "tsql/ast/generated/nodes.hpp"

namespace tsql::ast {

class TSqlFragmentVisitor {
public:
    virtual ~TSqlFragmentVisitor() = default;

    virtual void Visit(TSqlFragment* fragment);

#include "tsql/ast/generated/visitor_members.inc"

protected:
    TSqlFragmentVisitor() : TSqlFragmentVisitor(true) {}
    TSqlFragmentVisitor(const TSqlFragmentVisitor&) = default;
    TSqlFragmentVisitor& operator=(const TSqlFragmentVisitor&) = default;

    /// C# internal property VisitBaseType.
    bool VisitBaseType() const { return visitBaseType_; }

private:
    friend class TSqlConcreteFragmentVisitor;
    // C# internal constructor: only TSqlConcreteFragmentVisitor passes false.
    explicit TSqlFragmentVisitor(bool visitBaseType) : visitBaseType_(visitBaseType) {}

    bool visitBaseType_;
};

class TSqlConcreteFragmentVisitor : public TSqlFragmentVisitor {
public:
    using TSqlFragmentVisitor::ExplicitVisit;
    using TSqlFragmentVisitor::Visit;

#include "tsql/ast/generated/concrete_visitor_members.inc"

protected:
    TSqlConcreteFragmentVisitor() : TSqlFragmentVisitor(false) {}
};

}  // namespace tsql::ast
