#!/usr/bin/env python3
"""ANTLR 2 (SqlScriptDOM TSql<ver>.g, C# actions) -> ANTLR 4 (C++ target) converter.

Run by the build (src/parser/CMakeLists.txt) in three steps; every step reads its inputs from the
given directories, writes only into the given output directories and rewrites a file only when
its content changes:

    convert.py grammar --grammar G --ssd DIR --ast-enums enums.hpp --out DIR --report-dir DIR
        <G>.g -> <G>Lexer.g4, <G>Parser.g4, TSqlTokens.tokens (SqlScriptDOM's token numbering),
        <G>.support.json; <report-dir>/<G>.json holds the statistics (mechanical vs hand-fixed)
    convert.py antlr --grammar G --grammar-dir DIR --out DIR --java J --antlr-jar JAR [--parts N]
        ANTLR 4 tool -> <G>Lexer.{h,cpp}, <G>Parser.h, <G>Parser.cpp (static ATN data) and
        <G>Parser_1..N.cpp (the rules, split at rule boundaries into N parts of similar size)
    convert.py support --ssd DIR --ast-enums enums.hpp --out DIR <every G.support.json>
        CodeGenerationSupporter.h, TSqlParserResource.h, Keywords.h (lexer literals table),
        ParserEnums.h, OptionHelpers.h, shared by every grammar (union over all of them)

Grammars: TSql130, TSql140, TSql150, TSql160, TSql170, TSql180, TSqlFabricDW. Names derive from
the grammar (<G>Parser/<G>Lexer; superclasses <G>ParserBase and the shared TSqlLexerBase).

Hand fixes are applied on every run, from tools/g2to4/overrides/common/ (every grammar) and
overrides/<G>/ (one grammar; wins over common):
    parser_actions.txt   C++ replacements for actions. common: `=== <rule> * sha=<hash of the C#>`
                         replaces any action of the rule with that C# text; <G>: keyed by rule +
                         action id + hash (a changed grammar invalidates the override loudly)
    parser_rules/*.g4    whole-rule ANTLR 4 replacements; a first line `// g2to4: sha=<hash>` pins
                         them to the ANTLR 2 rule (required in common: applied only where it matches)
    lexer_rules/*.g4     whole-rule replacements for the lexers
    synpreds.txt         ANTLR 2 syntactic predicates to keep (as speculative parses); all others
                         are dropped and left to ANTLR 4's unbounded lookahead (a reference to the
                         empty rule SYNPRED_MARKER marks their alternatives)
Hand-written C++ the actions call: src/parser/TSql<ver>ParserBase.cpp (the C# base class chain
TSql80 -> ... -> TSql180, TSqlFabricDW -> TSql150; drafts come from tools/g2to4/portbase.py),
src/parser/helpers/ (C# helper classes and OptionsHelper members). The output is deterministic.
"""
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import antlr2  # noqa: E402
from antlr2 import (Action, Alt, Block, Literal, Not, Range, RuleRef, SemPred, SubRule, TokenRef,  # noqa: E402
                    Wildcard)
from cs2cpp import Scope, Translator, Untranslatable  # noqa: E402
from model import Model  # noqa: E402
import support  # noqa: E402
import lexer as lexconv  # noqa: E402

REPO = os.path.normpath(os.path.join(HERE, '..', '..'))
TOKENS_REL = 'SqlScriptDom/Parser/TSql/TSqlTokenTypes.g'
HEADER = '// Ported from Microsoft SqlScriptDOM (MIT) @ eaf3a6e: %s\n// GENERATED by tools/g2to4/convert.py. Do not edit; edit the converter or tools/g2to4/overrides.\n'

# ANTLR 2 guessing-mode helpers (SaveGuessing/SkipGuessing) only short-circuit nested syntactic
# predicates; with syntactic predicates gone they are no-ops.
GUESSING_INIT = re.compile(r'^\s*(if\s*\(\s*!\s*SkipGuessing\(\w+\)\s*\)|SaveGuessing\(\s*out\s+\w+\s*\)\s*;)\s*$')


def synpred_marker(name):
    """The empty rule whose reference starts the alternative of dropped syntactic predicate `name`
    (see Converter.load_synpreds)."""
    return 'antlr2SynPred_' + name


def rule_const(name):
    """The generated parser's rule index constant of rule `name` (ANTLR 4 C++ target)."""
    return 'Rule' + name[0].upper() + name[1:]


def top_synpreds(node):
    """The syntactic predicates under a Block/Alt/element in order, without those nested in one
    (the order RuleConverter numbers them in)."""
    if isinstance(node, Block):
        for a in node.alts:
            yield from top_synpreds(a)
    elif isinstance(node, Alt):
        for e in node.elems:
            yield from top_synpreds(e)
    elif isinstance(node, SubRule):
        if node.suffix == '=>':
            yield node
        else:
            yield from top_synpreds(node.block)
    elif isinstance(node, Not):
        yield from top_synpreds(node.elem)

# Handlers for exceptions that cannot occur in <G>Parser.Parse:
#  - TokenStreamRecognitionException: lexing finishes before parsing (TSqlParser.Parse), so the
#    parser never sees token stream errors;
#  - PhaseOne*: only thrown in phase-one mode (TSqlParser.PhaseOneParse, not ported).
DEAD_CATCH_TYPES = {'antlr.TokenStreamRecognitionException', 'PhaseOnePartialAstException',
                    'PhaseOneConstraintException'}

CATCH_TYPES = {
    'TSqlParseErrorException': 'TSqlParseErrorException',
    'antlr.NoViableAltException': 'antlr4::NoViableAltException',
    'antlr.MismatchedTokenException': 'antlr4::InputMismatchException',
    'antlr.RecognitionException': 'antlr4::RecognitionException',
    'antlr.ANTLRException': 'antlr4::RuntimeException',
}


def sha(text):
    return hashlib.sha1(re.sub(r'\s+', ' ', text).strip().encode()).hexdigest()[:8]


# ---------------------------------------------------------------------- token vocabulary

def token_vocab(ssd):
    g = antlr2.parse(open(os.path.join(ssd, TOKENS_REL), encoding='utf-8-sig').read())
    cls = g.classes[0]
    names, literals = [], {}
    for name, lit in cls.tokens:
        names.append(name)
        if lit is not None:
            literals[name] = lit
    # lexer rules that are not in tokens{} get the next numbers (ANTLR 2 rule order)
    for r in cls.rules:
        if r.name not in names:
            names.append(r.name)
    return [(n, i + 4) for i, n in enumerate(names)], literals


# ---------------------------------------------------------------------- overrides

def load_action_overrides(path):
    """{(rule, action id): (sha, C++)}. In overrides/common the id is `*`: the entry applies to
    every grammar whose rule has an action with that C# text (sha)."""
    ov = {}
    if not os.path.exists(path):
        return ov
    cur, buf = None, []
    for line in open(path, encoding='utf-8'):
        m = re.match(r'^=== (\w+) (\w+|\*) sha=([0-9a-f]{8})\s*$', line)
        if m:
            cur, buf = (m.group(1), m.group(2), m.group(3)), []
            continue
        if line.startswith('=== end') and cur:
            ov[(cur[0], cur[1])] = (cur[2], ''.join(buf).rstrip('\n'))
            cur = None
            continue
        if cur:
            buf.append(line)
    return ov


def load_common_action_overrides(path):
    """overrides/common/parser_actions.txt: {(rule, '*'): [(sha, C++)]}; an entry replaces any action
    of that rule whose C# text has the sha, in every grammar."""
    out = {}
    if os.path.exists(path):
        cur, buf = None, []
        for line in open(path, encoding='utf-8'):
            m = re.match(r'^=== (\w+) \* sha=([0-9a-f]{8})\s*$', line)
            if m:
                cur, buf = (m.group(1), m.group(2)), []
                continue
            if line.startswith('=== end') and cur:
                out.setdefault((cur[0], '*'), []).append((cur[1], ''.join(buf).rstrip('\n')))
                cur = None
                continue
            if cur:
                buf.append(line)
    return out


def load_rule_overrides(d):
    """{rule: (sha or None, ANTLR 4 text)}. A first line `// g2to4: sha=XXXXXXXX` pins the override
    to the ANTLR 2 rule it replaces (required in overrides/common)."""
    ov = {}
    if os.path.isdir(d):
        for f in sorted(os.listdir(d)):
            if f.endswith('.g4'):
                text = open(os.path.join(d, f), encoding='utf-8').read().rstrip('\n')
                m = re.match(r'// g2to4: sha=([0-9a-f]{8})\n', text)
                ov[f[:-3]] = (m.group(1) if m else None, text[m.end():] if m else text)
    return ov


def body_lines(text):
    return len([ln for ln in text.splitlines() if ln.strip() and not ln.strip().startswith('//')])


# ---------------------------------------------------------------------- parser conversion

class Param:
    def __init__(self, mode, cstype, name):
        self.mode, self.cstype, self.name = mode, cstype, name   # mode: 'val' | 'ptr'


def split_top(text, sep=','):
    parts, depth, cur = [], 0, ''
    for c in text:
        if c in '<([':
            depth += 1
        elif c in '>)]':
            depth -= 1
        if c == sep and depth == 0:
            parts.append(cur)
            cur = ''
        else:
            cur += c
    if cur.strip():
        parts.append(cur)
    return [p.strip() for p in parts]


def parse_params(text):
    out = []
    if not text:
        return out
    for p in split_top(text):
        words = p.split()
        mode = 'val'
        if words[0] in ('ref', 'out'):
            mode = 'ptr'
            words = words[1:]
        name = words[-1]
        cstype = ' '.join(words[:-1])
        if re.match(r'I?List<', cstype) or cstype.endswith('StringBuilder'):
            mode = 'ptr'   # C# reference types the callee mutates
        out.append(Param(mode, cstype, name))
    return out


def parse_returns(text):
    if not text:
        return None
    m = re.match(r'\s*(.+?)\s+(\w+)\s*(=\s*(.*))?$', text.strip(), re.S)
    return m.group(1), m.group(2), (m.group(4).strip() if m.group(4) else None)


class RuleConverter:
    def __init__(self, conv, rule):
        self.c, self.r = conv, rule
        self.tr = conv.tr
        self.counters = {'a': 0, 'p': 0, 'g': 0, 'h': 0, 'r': 0}
        self.issues = []          # (id, reason)
        self.overridden = []      # ids replaced by hand overrides
        self.hand_lines = 0
        self.actions_total = 0
        self.actions_auto = 0
        self.synpreds_dropped = 0
        self.labels = {}          # label -> kind
        self.synpred_index = 0
        self.rv = 0
        self.locals_decl = []
        # a syntactic predicate's block (Converter.load_synpreds): no actions, nothing assigned
        self.recognizer_only = rule.name in conv.synpred_blocks

    def aname(self, n):
        """Name of a parameter/return/label/local in the ANTLR rule context: ANTLR 4 rejects names
        that equal a rule or token name, so those get a trailing underscore (the C++ actions keep the
        C# name through a reference bound in @init)."""
        if n in self.c.P.rule_map or n in self.c.vocab_names:
            self.c.stats['renamed_context_names'] = self.c.stats.get('renamed_context_names', 0) + 1
            return n + '_'
        return n

    # -------------------------------------------------------------- scope
    def build_scope(self):
        r, tr = self.r, self.tr
        sc = Scope()
        self.params = parse_params(r.args)
        self.ret = parse_returns(r.returns)
        for p in self.params:
            cpp, kind = tr.cpp_type(p.cstype)
            sc.add(p.name, kind, cpp, ctx=True)
            if p.mode == 'ptr':
                sc.pred_alias[p.name] = '(*\x01p_%s)' % p.name
            elif self.aname(p.name) != p.name:
                sc.pred_alias[p.name] = '\x01' + self.aname(p.name)
        if self.ret:
            cpp, kind = tr.cpp_type(self.ret[0])
            sc.add(self.ret[1], kind, cpp, ctx=True)
            if self.aname(self.ret[1]) != self.ret[1]:
                sc.pred_alias[self.ret[1]] = '\x01' + self.aname(self.ret[1])
        for e in antlr2.walk(r.block):
            lab = getattr(e, 'label', None)
            if lab:
                if isinstance(e, RuleRef):
                    raise SystemExit('rule-ref label unsupported: %s in %s' % (lab, r.name))
                self.labels[lab] = 'tok'
                sc.add(lab, 'tok', 'antlr4::Token*', ctx=True)
                if self.aname(lab) != lab:
                    sc.pred_alias[lab] = '\x01' + self.aname(lab)
        # init-block locals read by predicates live in the rule context
        if r.init:
            decl_names = set(re.findall(r'\b\w[\w<>,\. ]*?\s+(\w+)\s*(?:=|;)', r.init))
            pred_text = ' '.join(e.text for e in antlr2.walk(r.block) if isinstance(e, SemPred))
            for n in sorted(decl_names):
                if re.search(r'\b%s\b' % re.escape(n), pred_text):
                    sc.ctx_locals.add(n)
                    if self.aname(n) != n:
                        sc.pred_alias[n] = '\x01' + self.aname(n)
        return sc

    # -------------------------------------------------------------- snippets
    def snippet(self, kind, text, mode):
        """Translate one action/predicate; applies overrides; records stats."""
        self.counters[kind] += 1
        aid = '%s%d' % (kind, self.counters[kind])
        self.actions_total += 1
        key = (self.r.name, aid)
        ov = self.c.action_overrides.get(key)
        if ov is None and (self.r.name, '*') in self.c.common_action_overrides:
            for h, txt in self.c.common_action_overrides[(self.r.name, '*')]:
                if h == sha(text):
                    ov = (h, txt)
                    self.c.used_common.add((self.r.name, h))
        if ov:
            h, txt = ov
            if h != sha(text):
                raise SystemExit('override %s %s: C# text changed (sha %s != %s)' % (key[0], aid, sha(text), h))
            self.c.used_overrides.add(key)
            self.overridden.append(aid)
            self.hand_lines += body_lines(txt)
            # keep the symbol table in sync with declarations in the original action
            try:
                self.tr.translate(text, self.scope, mode)
            except Untranslatable:
                pass
            return txt
        # An action may consume tokens (offsetClause: FETCH APPROX[IMATE] NEXT). ANTLR 2's lookahead
        # did not see them either, and the runtime decides as ANTLR 2 did (src/parser/ParserRuntime.cpp).
        try:
            out = self.tr.translate(text, self.scope, mode)
            self.actions_auto += 1
            return out
        except Untranslatable as ex:
            self.issues.append((aid, str(ex), sha(text)))
            src = re.sub(r'\*/', '* /', text.strip())
            return 'G2TO4_UNTRANSLATED("%s %s: %s"); /* C#: %s */' % (self.r.name, aid, str(ex).replace('"', "'"), src)

    @staticmethod
    def finish(text):
        text = text.replace('$', '\\$').replace('\x01', '$')
        return text

    # -------------------------------------------------------------- emission
    def convert(self):
        r, tr = self.r, self.tr
        self.scope = self.build_scope()
        sc = self.scope
        # signature
        args = []
        prologue = []
        for p in self.params:
            cpp, _ = tr.cpp_type(p.cstype)
            if p.mode == 'ptr':
                args.append('%s* p_%s' % (cpp, p.name))
                prologue.append('auto& %s = *p_%s;' % (p.name, p.name))
            else:
                args.append('%s %s' % (cpp, self.aname(p.name)))
                if self.aname(p.name) != p.name:
                    prologue.append('auto& %s = %s;' % (p.name, self.aname(p.name)))
        head = r.name
        if args:
            head += '[%s]' % ', '.join(args)
        init_lines = []
        if self.ret:
            cpp, kind = tr.cpp_type(self.ret[0])
            dflt = 'nullptr' if cpp.endswith('*') else ''
            head += ' returns [%s %s%s]' % (cpp, self.aname(self.ret[1]), (' = ' + dflt) if dflt else '')
            prologue.append('auto& %s = _localctx->%s;' % (self.ret[1], self.aname(self.ret[1])))
            if self.ret[2] and self.ret[2] != 'null':
                init_lines.append(self.snippet('g', '%s = %s;' % (self.ret[1], self.ret[2]), 'action'))
        for lab in sorted(self.labels):
            prologue.append('auto& %s = _localctx->%s;' % (lab, self.aname(lab)))
        # ctx locals: need declared types
        locals_ = []
        if sc.ctx_locals:
            for m in re.finditer(r'([\w\.]+(?:<[^>]*>)?(?:\[\])?\??)\s+(\w+)\s*(?:=|;)', r.init or ''):
                if m.group(2) in sc.ctx_locals:
                    cpp, kind = tr.cpp_type(m.group(1))
                    locals_.append('%s %s' % (cpp, self.aname(m.group(2))))
                    prologue.append('auto& %s = _localctx->%s;' % (m.group(2), self.aname(m.group(2))))
        if r.init:
            init_lines.append(self.snippet('g', r.init, 'action'))
        body = self.block(r.block, 1, top=True)
        handlers = []
        for arg, act in r.handlers:
            m = re.match(r'\s*([\w\.]+)\s*(\w*)\s*$', arg)
            cst, var = m.group(1), m.group(2)
            if cst in DEAD_CATCH_TYPES:
                self.c.stats['dropped_catch_clauses'] += 1
                continue
            cpp = CATCH_TYPES[cst]
            hs = sc.copy()
            if var:
                hs.add(var, 'exc', cpp)
            saved = self.scope
            self.scope = hs
            txt = self.snippet('h', act, 'action')
            self.scope = saved
            guard = 'if (Guessing()) throw; ' if r.name in self.c.guess_rules else ''
            handlers.append('catch [%s& %s] {%s%s}' % (cpp, var or 'e_', guard, self.finish(txt)))
        out = [head]
        if locals_:
            out.append('locals [%s]' % ', '.join(locals_))
        init = '\n    '.join(prologue + [self.finish(t).strip() for t in init_lines])
        if init:
            out.append('@init {\n    %s\n}' % init)
        out.append('    : ' + body)
        out.append('    ;')
        out.extend(handlers)
        return '\n'.join(out)

    def block(self, blk, depth, top=False):
        alts = [self.alt(a, depth) for a in blk.alts]
        sep = '\n' + '    ' * (depth if not top else 1) + '| '
        return sep.join(a if a.strip() else '/* empty */' for a in alts)

    def alt(self, alt, depth):
        parts = []
        elems = alt.elems
        i = 0
        while i < len(elems):
            e = elems[i]
            parts.append(self.elem(e, depth))
            i += 1
        return ' '.join(p for p in parts if p)

    def elem(self, e, depth):
        tr = self.tr
        if isinstance(e, TokenRef):
            if e.name not in self.c.vocab_names and e.name != 'EOF':
                # ANTLR 2 silently defines a new token type the lexer never produces
                self.c.implicit_tokens.add(e.name)
            return ('%s=%s' % (self.aname(e.label), e.name)) if e.label else e.name
        if isinstance(e, RuleRef):
            callee = self.c.P.rule_map[e.name]
            cparams = parse_params(callee.args)
            args = ''
            if e.args:
                self.counters['r'] += 1
                aid = 'r%d' % self.counters['r']
                self.actions_total += 1
                key = (self.r.name, aid)
                ov = self.c.action_overrides.get(key)
                if ov:
                    self.c.used_overrides.add(key)
                    self.overridden.append(aid)
                    self.hand_lines += body_lines(ov[1])
                    args = '[%s]' % ov[1]
                else:
                    try:
                        args = '[%s]' % self.finish(tr.translate_rule_args(
                            e.args, self.scope, [('ptr' if p.mode == 'ptr' else 'val', p) for p in cparams]))
                        self.actions_auto += 1
                    except Untranslatable as ex:
                        self.issues.append((aid, str(ex), sha(e.args)))
                        args = '[G2TO4_UNTRANSLATED("%s")]' % ex
            if e.assign and not self.recognizer_only:
                cret = parse_returns(callee.returns)
                if not cret:
                    raise SystemExit('%s assigns from %s which returns nothing' % (self.r.name, e.name))
                self.rv += 1
                lab = 'rv%d' % self.rv
                return '%s=%s%s {%s = $%s.%s;}' % (lab, e.name, args, e.assign, lab, RuleConverter(self.c, callee).aname(cret[1]))
            return e.name + args
        if isinstance(e, Action):
            m = re.match(r'^\s*([\w\.]+)\s*=\s*([a-z]\w*)\s*\((.*)\)\s*;\s*$', e.text, re.S)
            if m and m.group(2) in self.c.P.rule_map:
                # C# action invoking a rule method directly: make it a rule reference so ANTLR 4's
                # prediction sees the tokens it consumes
                self.c.stats['action_rule_calls_to_refs'] += 1
                lhs, rule, args = m.group(1), m.group(2), m.group(3).strip() or None
                if '.' not in lhs or self.recognizer_only:
                    return self.elem(RuleRef(rule, assign=lhs, args=args), depth)
                ref = self.elem(RuleRef(rule, args=args), depth)
                cret = parse_returns(self.c.P.rule_map[rule].returns)
                self.rv += 1
                lab = 'rv%d' % self.rv
                act = self.finish(self.snippet('a', '%s = G2TO4_RV;' % lhs, 'action'))
                act = act.replace('G2TO4_RV', '$%s.%s' % (lab, RuleConverter(self.c, self.c.P.rule_map[rule]).aname(cret[1])))
                return '%s=%s {%s}' % (lab, ref, act)
            if self.recognizer_only:
                # a syntactic predicate's block: ANTLR 2 runs it only while guessing, without actions
                return ''
            txt = self.finish(self.snippet('a', e.text, 'action'))
            if self.r.name in self.c.guess_rules:
                # ANTLR 2 skips actions while guessing (inside a syntactic predicate)
                return '{if (!Guessing()) {%s}}' % txt
            return '{%s}' % txt
        if isinstance(e, SemPred):
            return '{%s}?' % self.finish(self.snippet('p', e.text, 'pred')).strip()
        if isinstance(e, SubRule):
            if e.suffix == '=>':
                self.synpred_index += 1
                kept = self.c.kept_synpreds.get((self.r.name, self.synpred_index))
                if kept:
                    # kept: a gated predicate that parses the ANTLR 2 lookahead speculatively
                    self.c.stats['synpreds_kept'] += 1
                    return '{Speculate(%s, [this] { %s(); })}?' % (rule_const(kept), kept)
                self.synpreds_dropped += 1
                self.c.stats['synpreds_dropped'] += 1
                dropped = self.c.dropped_synpreds.get((self.r.name, self.synpred_index))
                # nested in another syntactic predicate: left to ANTLR 4's lookahead
                return synpred_marker(dropped) if dropped else ''
            pre = ''
            if e.block.init:
                if GUESSING_INIT.match(e.block.init):
                    self.c.stats['guessing_inits_dropped'] += 1
                else:
                    pre = '' if self.recognizer_only else '{%s} ' % self.finish(self.snippet('a', e.block.init, 'action'))
            suffix = e.suffix
            if e.block.options.get('greedy') == 'false':
                if suffix in ('*', '+', '?'):
                    suffix += '?'
                self.c.stats['nongreedy'] += 1
            elif 'greedy' in e.block.options:
                self.c.stats['greedy_true_dropped'] += 1
            inner = self.block(e.block, depth + 1)
            ind = '    ' * (depth + 1)
            if '\n' in inner or len(inner) > 80:
                return '%s(\n%s  %s\n%s)%s' % (pre, ind, inner, ind, suffix)
            return '%s(%s)%s' % (pre, inner, suffix)
        if isinstance(e, Not):
            return '~' + self.elem(e.elem, depth)
        if isinstance(e, Wildcard):
            return '.'
        if isinstance(e, (Literal, Range)):
            raise SystemExit('literal in parser rule %s' % self.r.name)
        raise SystemExit('unhandled element %r' % e)


class Converter:
    def __init__(self, ssd, ast_enums, grammar):
        self.ssd = ssd
        self.grammar = grammar                       # e.g. TSql170
        self.grammar_rel = 'SqlScriptDom/Parser/TSql/%s.g' % grammar
        self.parser_name = grammar + 'Parser'
        self.lexer_name = grammar + 'Lexer'
        self.overrides_dir = os.path.join(HERE, 'overrides', grammar)
        self.common_dir = os.path.join(HERE, 'overrides', 'common')
        src = open(os.path.join(ssd, self.grammar_rel), encoding='utf-8-sig').read()
        self.g = antlr2.parse(src)
        self.P, self.L = self.g.classes
        self.model = Model(ssd, ast_enums)
        self.vocab, self.vocab_literals = token_vocab(ssd)
        self.vocab_names = {n for n, _ in self.vocab}
        self.tr = Translator(self.model, self.vocab_names, self.parser_name)
        self.action_overrides = load_action_overrides(os.path.join(self.overrides_dir, 'parser_actions.txt'))
        self.common_action_overrides = load_common_action_overrides(os.path.join(self.common_dir, 'parser_actions.txt'))
        self.used_common = set()
        # grammar-specific rule overrides win over common ones; common ones apply only where the
        # ANTLR 2 rule is identical (sha)
        self.rule_overrides = {}
        for name, (h, text) in load_rule_overrides(os.path.join(self.common_dir, 'parser_rules')).items():
            if h is None:
                raise SystemExit('overrides/common/parser_rules/%s.g4 needs a `// g2to4: sha=` line' % name)
            if name in self.P.rule_map and self.P.rule_map[name].sha == h:
                self.rule_overrides[name] = text
        for name, (h, text) in load_rule_overrides(os.path.join(self.overrides_dir, 'parser_rules')).items():
            if h is not None and name in self.P.rule_map and self.P.rule_map[name].sha != h:
                raise SystemExit('overrides/%s/parser_rules/%s.g4: ANTLR 2 rule changed (sha %s != %s)'
                                 % (grammar, name, self.P.rule_map[name].sha, h))
            self.rule_overrides[name] = text
        self.used_overrides = set()
        self.implicit_tokens = set()
        self.load_synpreds()
        self.stats = {k: 0 for k in ('synpreds_dropped', 'guessing_inits_dropped', 'nongreedy',
                                     'greedy_true_dropped', 'dropped_catch_clauses', 'action_rule_calls_to_refs',
                                     'synpreds_kept')}

    def load_synpreds(self):
        """Every syntactic predicate of a rule R (the N-th, 1-based, not nested in another) becomes
        rule R_synpredN, which parses its block without actions (ANTLR 2 runs it only while
        guessing, when actions are skipped). overrides/<G>/synpreds.txt `R N` keeps it as a gated
        predicate, a speculative parse ANTLR 4 runs while predicting. Every other one is dropped
        from ANTLR 4's view and left to its unbounded lookahead; its alternative starts with a
        reference to the empty rule synpred_marker(R_synpredN), through which the runtime's
        emulation of ANTLR 2's decisions (src/parser/ParserRuntime.cpp) runs the speculative parse
        where ANTLR 2 would have (the generated parser's Antlr2SynPred)."""
        kept = set()
        for path in (os.path.join(self.common_dir, 'synpreds.txt'), os.path.join(self.overrides_dir, 'synpreds.txt')):
            if not os.path.exists(path):
                continue
            for line in open(path, encoding='utf-8'):
                line = line.split('#', 1)[0].strip()
                if line:
                    rule, n = line.split()
                    if rule in self.P.rule_map:
                        kept.add((rule, int(n)))
        self.kept_synpreds = {}       # (rule, n) -> synthetic rule name
        self.dropped_synpreds = {}    # (rule, n) -> synthetic rule name
        self.synpred_blocks = {}      # synthetic rule name -> Block
        self.synpred_owner = {}       # synthetic rule name -> the ANTLR 2 rule it is in
        for r in self.P.rules:
            for n, pred in enumerate(top_synpreds(r.block), 1):
                name = '%s_synpred%d' % (r.name, n)
                (self.kept_synpreds if (r.name, n) in kept else self.dropped_synpreds)[(r.name, n)] = name
                self.synpred_blocks[name] = pred.block
                self.synpred_owner[name] = r
        missing = kept - set(self.kept_synpreds)
        if missing:
            raise SystemExit('synpreds.txt: no such syntactic predicate: %s' % sorted(missing))
        # rules that can run while guessing: their actions are skipped then
        work = [e.name for b in self.synpred_blocks.values() for e in antlr2.walk(b) if isinstance(e, RuleRef)]
        self.guess_rules = set(self.synpred_blocks)
        while work:
            n = work.pop()
            if n not in self.guess_rules:
                self.guess_rules.add(n)
                work.extend(e.name for e in antlr2.walk(self.P.rule_map[n].block) if isinstance(e, RuleRef))

    def synpred_dispatch(self):
        """Named actions declaring and defining the generated parser's Antlr2SynPred(marker, ctx)
        (TSql80ParserBase): the speculative parse of the dropped syntactic predicate whose marker
        rule is `marker`, called with the arguments of its rule's context `ctx`."""
        cases = []
        for name in sorted(self.dropped_synpreds.values()):
            owner = self.synpred_owner[name]
            rc = RuleConverter(self, owner)
            fields = ['c->' + ('p_' + p.name if p.mode == 'ptr' else rc.aname(p.name)) for p in parse_params(owner.args)]
            marker = synpred_marker(name)
            if fields:
                call = ('if (auto* c = dynamic_cast<%sContext*>(ctx)) return Speculate(%s, [&] { %s(%s); });\n'
                        '        return true;' % (owner.name[0].upper() + owner.name[1:], rule_const(name), name,
                                                  ', '.join(fields)))
            else:
                call = 'return Speculate(%s, [this] { %s(); });' % (rule_const(name), name)
            cases.append('    case %s:\n        %s' % (rule_const(marker), call))
        return ('@parser::members {\nbool Antlr2SynPred(size_t marker, antlr4::ParserRuleContext* ctx) override;\n}\n',
                '@parser::definitions {\nbool %s::Antlr2SynPred(size_t marker, [[maybe_unused]] antlr4::ParserRuleContext* ctx) {\n'
                '    switch (marker) {\n%s\n    }\n    return true;\n}\n}\n' % (self.parser_name, '\n'.join(cases)))

    def parser_grammar(self):
        P = self.P
        self.rule_reports = {}
        out = [HEADER % self.grammar_rel,
               'parser grammar %s;\n' % self.parser_name,
               'options { tokenVocab = %s; superClass = %sBase; }\n' % (self.lexer_name, self.parser_name),
               '@parser::header {\n#include "%sBase.h"\n}\n' % self.parser_name,
               '@parser::postinclude {\nusing namespace tsql::parser;\nnamespace ast = tsql::ast;\n}\n']
        out.extend(self.synpred_dispatch())
        for r in P.rules:
            name = r.name
            rc = RuleConverter(self, r)
            if name in self.rule_overrides:
                text = self.rule_overrides[name]
                rep = dict(status='rule_override', hand_lines=body_lines(text), src_lines=r.src_lines)
                rc.convert()   # still run for symbol/statistics side effects
                rep['actions_total'] = rc.actions_total
            else:
                try:
                    text = rc.convert()
                except Untranslatable as ex:
                    rc.issues.append(('signature', str(ex), sha(r.args or '' + (r.returns or ''))))
                    text = '%s : G2TO4_UNTRANSLATED_SIGNATURE ;' % name
                status = 'mechanical'
                if rc.overridden:
                    status = 'action_overrides'
                if rc.issues:
                    status = 'untranslated'
                rep = dict(status=status, hand_lines=rc.hand_lines, src_lines=r.src_lines,
                           actions_total=rc.actions_total, actions_auto=rc.actions_auto,
                           overridden=rc.overridden, issues=rc.issues)
            self.rule_reports[name] = rep
            out.append(text + '\n')
        for (rule, n), name in sorted(self.dropped_synpreds.items()):
            out.append('// Starts the alternative of %s, dropped syntactic predicate %d of %s (matches nothing)\n%s : ;\n'
                       % (name, n, rule, synpred_marker(name)))
        for name in sorted(self.synpred_blocks):
            owner = self.synpred_owner[name]
            r = antlr2.Rule()
            r.name, r.block = name, self.synpred_blocks[name]
            if name in self.dropped_synpreds.values():
                r.args = owner.args   # Antlr2SynPred passes those of the rule's context
            out.append('// ANTLR 2 syntactic predicate of %s, parsed speculatively\n%s\n'
                       % (owner.name, RuleConverter(self, r).convert()))
        if self.implicit_tokens:
            out.insert(4, '// Implicitly defined by ANTLR 2 (not in TSqlTokenTypes.g; the lexer never produces them)\n'
                          'tokens { %s }\n' % ', '.join(sorted(self.implicit_tokens)))
        self.stats['implicit_tokens'] = sorted(self.implicit_tokens)
        unused = set(self.action_overrides) - self.used_overrides
        unused_rules = set(self.rule_overrides) - set(P.rule_map)
        if unused or unused_rules:
            raise SystemExit('unused overrides: %s' % sorted(unused | unused_rules))
        return '\n'.join(out)


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = open(path, encoding='utf-8').read() if os.path.exists(path) else None
    if old != text:
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)


GRAMMARS = ['TSql130', 'TSql140', 'TSql150', 'TSql160', 'TSql170', 'TSql180', 'TSqlFabricDW']
PARSER_PARTS = 5   # default number of rule translation units per generated parser (--parts)


def split_parser_cpp(src, parser_name, n_parts):
    """Splits ANTLR's <G>Parser.cpp into 1 + n_parts translation units at rule boundaries (the
    `//----------------- XContext ---` separators). Part 0 keeps the static ATN data (anonymous
    namespace), constructor and initialize(); parts 1..n_parts get the include/using prologue and
    a share of the rules of similar size (a section goes to the part its first line falls in).
    The count is fixed so the build knows the file list in advance; deterministic."""
    lines = src.split('\n')
    head_end = lines.index('namespace {')
    sep = [i for i, ln in enumerate(lines) if ln.startswith('//----------------- ')]
    sempred = next(i for i, ln in enumerate(lines) if ln.startswith('bool %s::sempred(' % parser_name))
    init = next(i for i, ln in enumerate(lines) if ln.startswith('void %s::initialize() {' % parser_name))
    assert sep and sep[0] > head_end and sempred > sep[-1] and init > sempred
    sections = [(sep[k], sep[k + 1] if k + 1 < len(sep) else sempred) for k in range(len(sep))]
    sections.append((sempred, init))
    total = init - sep[0]
    parts = [[] for _ in range(n_parts)]
    for a, b in sections:
        parts[min(n_parts - 1, (a - sep[0]) * n_parts // total)].append((a, b))
    if not all(parts):
        raise SystemExit('%s: cannot split into %d non-empty parts' % (parser_name, n_parts))
    prologue = '\n'.join(lines[:head_end]) + '\n'
    out = ['\n'.join(lines[:sep[0]] + lines[init:])]
    for k, part in enumerate(parts, 1):
        body = '\n'.join('\n'.join(lines[a:b]) for a, b in part)
        out.append('// Part %d of %s.cpp, split by tools/g2to4/convert.py (split_parser_cpp).\n%s\n%s\n'
                   % (k, parser_name, prologue, body))
    return out


def antlr_outputs(grammar, n_parts):
    """File names `antlr` writes for a grammar (the build lists them at configure time)."""
    return ['%sLexer.h' % grammar, '%sLexer.cpp' % grammar, '%sParser.h' % grammar, '%sParser.cpp' % grammar] + \
        ['%sParser_%d.cpp' % (grammar, k) for k in range(1, n_parts + 1)]


def run_antlr(java, jar, gdir, outdir, grammar, n_parts):
    """Runs the ANTLR 4 tool (C++ target) on <gdir>/<G>Lexer.g4 + <G>Parser.g4 and writes the
    lexer, the parser header and the parser split into 1 + n_parts translation units to outdir."""
    lexer_name, parser_name = grammar + 'Lexer', grammar + 'Parser'
    with tempfile.TemporaryDirectory() as tmp:
        cmd = [java, '-Xss64m', '-jar', jar, '-Dlanguage=Cpp', '-package', 'tsql::parser', '-no-listener', '-no-visitor',
               '-long-messages', '-o', tmp, '-Xexact-output-dir', lexer_name + '.g4', parser_name + '.g4']
        p = subprocess.run(cmd, cwd=gdir, capture_output=True, encoding='utf-8', errors='replace')
        out = (p.stdout + p.stderr).strip()
        if p.returncode != 0:
            raise SystemExit('ANTLR tool failed:\n' + out)
        files = {}
        for f in [n + ext for n in (lexer_name, parser_name) for ext in ('.cpp', '.h')]:
            src = open(os.path.join(tmp, f), encoding='utf-8').read()
            # ANTLR stamps the absolute grammar path; keep the output reproducible
            src = re.sub(r'^// Generated from .*$', '// Generated from %s by ANTLR 4.13.2 (tools/g2to4/convert.py)'
                         % f.replace('.cpp', '.g4').replace('.h', '.g4'), src, count=1, flags=re.M)
            files[f] = src
    parts = split_parser_cpp(files.pop(parser_name + '.cpp'), parser_name, n_parts)
    for k, text in enumerate(parts):
        files['%s%s.cpp' % (parser_name, '' if k == 0 else '_%d' % k)] = text
    assert sorted(files) == sorted(antlr_outputs(grammar, n_parts))
    for f, text in files.items():
        write(os.path.join(outdir, f), text)
    msgs = [ln for ln in out.splitlines() if ln.strip()]
    if msgs:
        print('\n'.join(msgs))
    return {'messages': msgs, 'warnings': sum(1 for m in msgs if m.startswith('warning')),
            'errors': sum(1 for m in msgs if m.startswith('error')),
            'parser_translation_units': len(parts),
            'generated_lines': {f: text.count('\n') for f, text in sorted(files.items())}}


class SupportInputs:
    """What the shared support code needs from all grammars (each grammar's support-inputs file)."""

    def __init__(self, ssd, model, inputs):
        self.ssd, self.model = ssd, model
        self.keyword_sets = [(r['grammar_rel'], r['lexer_literals']) for r in inputs]
        self.static_classes = sorted(set().union(*[r['static_classes_referenced'] for r in inputs]))
        self.parser_enums = sorted(set().union(*[r['parser_enums'] for r in inputs]))


def dump_json(path, data):
    write(path, json.dumps(data, indent=1, sort_keys=True) + '\n')


def cmd_grammar(a):
    """<G>.g -> <out>/<G>Lexer.g4, <G>Parser.g4, TSqlTokens.tokens, <G>.support.json (what the
    shared support code needs) and <report-dir>/<G>.json (statistics)."""
    conv = Converter(a.ssd, a.ast_enums, a.grammar)
    write(os.path.join(a.out, 'TSqlTokens.tokens'), ''.join('%s=%d\n' % (n, v) for n, v in conv.vocab))
    write(os.path.join(a.out, conv.parser_name + '.g4'), conv.parser_grammar())
    lx = lexconv.convert_lexer(conv, [os.path.join(conv.overrides_dir, 'lexer_rules'),
                                      os.path.join(conv.common_dir, 'lexer_rules')])
    write(os.path.join(a.out, conv.lexer_name + '.g4'), lx.text)
    reps = conv.rule_reports

    def count(st):
        return sum(1 for v in reps.values() if v['status'] == st)
    lits = dict(conv.vocab_literals)
    lits.update({n: v for n, v in conv.L.tokens if v is not None})
    dump_json(os.path.join(a.out, a.grammar + '.support.json'), {
        'grammar_rel': conv.grammar_rel,
        'lexer_literals': lits,
        'static_classes_referenced': sorted(conv.tr.static_classes_used),
        'parser_enums': sorted(conv.tr.parser_enums_used),
    })
    report = {
        'grammar': conv.grammar,
        'parser_rules_emitted': len(reps),
        'parser_source_lines': sum(v['src_lines'] for v in reps.values()),
        'rules_mechanical': count('mechanical'),
        'rules_with_action_overrides': count('action_overrides'),
        'rules_whole_override': count('rule_override'),
        'rules_untranslated': count('untranslated'),
        'hand_lines_parser': sum(v['hand_lines'] for v in reps.values()),
        'snippets_total': sum(v.get('actions_total', 0) for v in reps.values()),
        'snippets_auto': sum(v.get('actions_auto', 0) for v in reps.values()),
        'snippets_overridden': sum(len(v.get('overridden', [])) for v in reps.values()),
        'snippets_untranslated': sum(len(v.get('issues', [])) for v in reps.values()),
        'common_action_overrides_used': len(conv.used_common),
        'stats': conv.stats,
        'lexer': lx.report,
        'rules': reps,
    }
    dump_json(os.path.join(a.report_dir, a.grammar + '.json'), report)
    bad = [(n, v['issues']) for n, v in reps.items() if v.get('issues')]
    for n, iss in bad:
        for aid, why, h in iss:
            print('UNTRANSLATED %s %s %s sha=%s: %s' % (a.grammar, n, aid, h, why))
    print('g2to4 %s: %d rules (%d mechanical, %d action overrides, %d rule overrides, %d untranslated), '
          '%d/%d snippets automatic' % (a.grammar, len(reps), report['rules_mechanical'],
                                        report['rules_with_action_overrides'], report['rules_whole_override'],
                                        report['rules_untranslated'], report['snippets_auto'], report['snippets_total']))
    if bad and a.strict:
        raise SystemExit('%s: untranslated actions (see above)' % a.grammar)


def cmd_antlr(a):
    rep = run_antlr(a.java, a.antlr_jar, a.grammar_dir, a.out, a.grammar, a.parts)
    if rep['errors'] or (rep['warnings'] and a.strict):
        raise SystemExit('%s: ANTLR reported %d errors, %d warnings' % (a.grammar, rep['errors'], rep['warnings']))
    if a.report:
        dump_json(a.report, rep)


def cmd_support(a):
    inputs = [json.load(open(f, encoding='utf-8')) for f in a.inputs]
    model = Model(a.ssd, a.ast_enums)
    sup = support.generate(SupportInputs(a.ssd, model, inputs), a.out)
    if a.report:
        dump_json(a.report, sup)
    for i in sup['helper_issues']:
        print('HELPER ' + i)
    if sup['helper_issues'] and a.strict:
        raise SystemExit('support: helper classes need hand ports (see above)')


def main():
    ap = argparse.ArgumentParser(description='SqlScriptDOM ANTLR 2 grammar -> ANTLR 4 (C++) converter')
    sub = ap.add_subparsers(dest='cmd', required=True)
    g = sub.add_parser('grammar', help='convert <G>.g to ANTLR 4 grammars')
    g.add_argument('--grammar', required=True, choices=GRAMMARS)
    g.add_argument('--ssd', required=True, help='SqlScriptDOM source tree')
    g.add_argument('--ast-enums', required=True, help="the AST's generated enums.hpp (tools/astgen)")
    g.add_argument('--out', required=True, help='output directory for the .g4 files')
    g.add_argument('--report-dir', required=True, help='output directory for <G>.json statistics')
    g.add_argument('--strict', action='store_true', help='fail on untranslated actions')
    g.set_defaults(fn=cmd_grammar)
    t = sub.add_parser('antlr', help='run the ANTLR 4 tool and split the parser into translation units')
    t.add_argument('--grammar', required=True, choices=GRAMMARS)
    t.add_argument('--grammar-dir', required=True, help='directory holding <G>Lexer.g4, <G>Parser.g4, TSqlTokens.tokens')
    t.add_argument('--out', required=True, help='output directory for the C++ sources')
    t.add_argument('--java', required=True)
    t.add_argument('--antlr-jar', required=True)
    t.add_argument('--parts', type=int, default=PARSER_PARTS, help='rule translation units (default %(default)s)')
    t.add_argument('--report', help='write ANTLR messages and file sizes here (JSON)')
    t.add_argument('--strict', action='store_true', help='fail on ANTLR warnings')
    t.set_defaults(fn=cmd_antlr)
    u = sub.add_parser('support', help='generate the support code shared by every grammar')
    u.add_argument('--ssd', required=True, help='SqlScriptDOM source tree')
    u.add_argument('--ast-enums', required=True, help="the AST's generated enums.hpp (tools/astgen)")
    u.add_argument('--out', required=True, help='output directory (CodeGenerationSupporter.h, ...)')
    u.add_argument('--report', help='write statistics here (JSON)')
    u.add_argument('--strict', action='store_true', help='fail when helper classes need hand ports')
    u.add_argument('inputs', nargs='+', help="every grammar's <G>.support.json")
    u.set_defaults(fn=cmd_support)
    a = ap.parse_args()
    a.fn(a)


if __name__ == '__main__':
    main()
