"""Mechanical C++ ports of the C# support classes the converted grammar actions reference:
CodeGenerationSupporter (string constants), TSqlParserResource (error message templates),
parser-side C# enums (SubDmlFlags, ...), the keyword literal table of the lexer and the
OptionsHelper<T> subclasses' option tables."""
import os
import re
import xml.etree.ElementTree as ET

from model import read_text

HDR = '// Ported from Microsoft SqlScriptDOM (MIT) @ eaf3a6e: %s\n// GENERATED by tools/g2to4/convert.py. Do not edit.\n'


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    old = open(path).read() if os.path.exists(path) else None
    if old != text:
        with open(path, 'w') as f:
            f.write(text)


def strip_cs_comments(t):
    t = re.sub(r'/\*.*?\*/', '', t, flags=re.S)
    return re.sub(r'//[^\n]*', '', t)


def gen_cgs(ssd, out):
    rel = 'SqlScriptDom/Parser/TSql/CodeGenerationSupporter.cs'
    src = strip_cs_comments(open(os.path.join(ssd, rel), encoding='utf-8-sig').read())
    items = re.findall(r'internal const string (\w+)\s*=\s*("(?:[^"\\]|\\.)*")\s*;', src)
    lines = [HDR % rel, '#pragma once\n\nnamespace tsql::parser {\n\nstruct CodeGenerationSupporter {\n']
    for n, v in items:
        lines.append('    static constexpr const char* %s = %s;\n' % (n, v))
    lines.append('};\n\n}  // namespace tsql::parser\n')
    write(os.path.join(out, 'CodeGenerationSupporter.h'), ''.join(lines))
    return len(items)


def gen_resources(ssd, out):
    rel = 'SqlScriptDom/TSqlParserResource.resx'
    root = ET.parse(os.path.join(ssd, rel)).getroot()
    lines = [HDR % rel, '#pragma once\n\nnamespace tsql::parser {\n\nstruct TSqlParserResource {\n']
    n = 0
    for d in root.findall('data'):
        v = d.find('value').text or ''
        v = v.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r')
        lines.append('    static constexpr const char* %s = "%s";\n' % (d.get('name'), v))
        n += 1
    lines.append('};\n\n}  // namespace tsql::parser\n')
    write(os.path.join(out, 'TSqlParserResource.h'), ''.join(lines))
    return n


def enum_values(body):
    vals, cur, out = {}, -1, []
    for item in [x.strip() for x in body.split(',') if x.strip()]:
        if '=' in item:
            name, expr = [x.strip() for x in item.split('=', 1)]
            e = expr
            for k in sorted(vals, key=len, reverse=True):
                e = re.sub(r'\b%s\b' % k, str(vals[k]), e)
            e = re.sub(r'\b\w+\.(\w+)\b', lambda m: str(vals[m.group(1)]), e)
            e = re.sub(r'(0x[0-9a-fA-F]+|\d+)[uUlL]+', r'\1', e)
            cur = eval(e)
        else:
            name = item
            cur += 1
        vals[name] = cur
        out.append((name, cur))
    return out


def gen_parser_enums(model, used, out):
    lines = [HDR % 'SqlScriptDom/Parser/TSql/*.cs (internal enums used by grammar actions)',
             '#pragma once\n\n#include <cstdint>\n\n#include "CsCompat.h"\n\nnamespace tsql::parser {\n\n']
    names = sorted(set(used) | set(model.parser_enums))
    for n in names:
        d = next((x for x in model.cs_enums[n] if not x['nested']), model.cs_enums[n][0])
        under = {'long': 'std::int64_t', 'ulong': 'std::uint64_t', 'int': 'std::int32_t', None: 'std::int32_t',
                 'byte': 'std::uint8_t', 'short': 'std::int16_t'}[d['underlying']]
        lines.append('// %s\nenum class %s : %s {\n' % (d['file'], n, under))
        for name, v in enum_values(d['body']):
            lines.append('    %s = %s,\n' % (name, hex(v) if v >= 0 else str(v)))
        lines.append('};\n')
        # C# permits bitwise operators on every enum
        for op in ('|', '&', '^'):
            lines.append('constexpr %s operator%s(%s a, %s b) { return static_cast<%s>(static_cast<%s>(a) %s static_cast<%s>(b)); }\n'
                         % (n, op, n, n, n, under, op, under))
            lines.append('constexpr %s& operator%s=(%s& a, %s b) { return a = a %s b; }\n' % (n, op, n, n, op))
        lines.append('constexpr %s operator~(%s a) { return static_cast<%s>(~static_cast<%s>(a)); }\n'
                     % (n, n, n, under))
        lines.append('constexpr bool operator!(%s a) { return static_cast<%s>(a) == 0; }\n' % (n, under))
        # names for Enum.TryParse / ToString
        lines.append('template <> struct EnumNames<%s> {\n    static constexpr EnumName<%s> entries[] = {\n' % (n, n))
        for name, v in enum_values(d['body']):
            lines.append('        {"%s", %s::%s},\n' % (name, n, name))
        lines.append('    };\n};\n\n')
    lines.append('}  // namespace tsql::parser\n')
    write(os.path.join(out, 'ParserEnums.h'), ''.join(lines))
    return names


def gen_keywords(ctx, out):
    """ANTLR 2 literals table (testLiterals) of the lexers: TSqlTokenTypes.g literals plus each
    grammar's tokens{} block. Shared by every lexer, so all grammars must agree."""
    tables = {}
    for grammar_rel, lits in ctx.keyword_sets:
        tables.setdefault(tuple(sorted(lits.items())), []).append(grammar_rel)
    if len(tables) != 1:
        raise SystemExit('lexer keyword tables differ between grammars: %s' % list(tables.values()))
    lits = dict(next(iter(tables)))
    items = sorted((v.lower(), k) for k, v in lits.items())
    lines = [HDR % 'SqlScriptDom/Parser/TSql/TSqlTokenTypes.g + the tokens{} block of every lexer (identical; ANTLR 2 literals table)',
             '#pragma once\n\n#include "tsql/ast/generated/token_types.hpp"\n\nnamespace tsql::parser {\n\n',
             'struct KeywordEntry { const char* text; ::tsql::ast::TSqlTokenType type; };\n\n',
             '// Sorted by text (lower case) for binary search.\n',
             'inline constexpr KeywordEntry kKeywords[] = {\n']
    for t, k in items:
        lines.append('    {"%s", ::tsql::ast::TSqlTokenType::%s},\n' % (t, k))
    lines.append('};\n\n}  // namespace tsql::parser\n')
    write(os.path.join(out, 'Keywords.h'), ''.join(lines))
    return len(items), {k: v.lower() for k, v in lits.items()}


def find_cs_class(ssd, name):
    base = os.path.join(ssd, 'SqlScriptDom')
    rx = re.compile(r'class\s+%s\b' % re.escape(name))
    for dp, _, fs in os.walk(base):
        for f in sorted(fs):
            if f.endswith('.cs'):
                p = os.path.join(dp, f)
                t = read_text(p)
                if rx.search(t):
                    return p, t
    return None, None


def cs_arg(a, kwmap, model):
    a = a.strip()
    parts = [p.strip() for p in a.split('+')]
    outs = []
    for p in parts:
        m = re.match(r'CodeGenerationSupporter\.(\w+)$', p)
        if m:
            outs.append('CodeGenerationSupporter::' + m.group(1))
            continue
        m = re.match(r'TSqlTokenType\.(\w+)$', p)
        if m:
            outs.append('"%s"' % kwmap[m.group(1)])
            continue
        m = re.match(r'(\w+)\.(\w+)$', p)
        if m and model.enum_kind(m.group(1)):
            pre = 'ast::' if model.enum_kind(m.group(1)) == 'ast' else ''
            if pre == '':
                model.use_parser_enum(m.group(1))
            outs.append('%s%s::%s' % (pre, m.group(1), m.group(2)))
            continue
        if p in ('string.Empty', 'String.Empty'):
            outs.append('""')
            continue
        if re.match(r'"[^"]*"$', p):
            outs.append(p)
            continue
        raise ValueError('helper arg ' + a)
    if len(outs) > 1:
        return 'std::string(%s)' % ') + std::string('.join(outs)
    return outs[0]


def gen_helpers(ctx, kwmap, out, hand_dir):
    """OptionsHelper<T> subclasses are generated (constructor mapping tables); their other members
    and every other static class the actions use are hand ports in src/parser/helpers:
    <Name>.inc (members included into the generated class) or <Name>.h (whole class)."""
    model = ctx.model
    used = set(ctx.static_classes)
    # helpers the hand-ported parser base uses (XHelper::Instance())
    for f in sorted(os.listdir(os.path.join(conv_repo(), 'src/parser'))):
        if f.endswith(('.cpp', '.h')):
            used |= set(re.findall(r'\b(\w+Helper)::Instance\(\)', read_text(os.path.join(conv_repo(), 'src/parser', f))))
    used = sorted(used)
    decl = [HDR % 'SqlScriptDom/Parser/TSql/*Helper.cs (OptionsHelper subclasses)',
            '#pragma once\n\n#include <string>\n\n#include "OptionsHelper.h"\n#include "CodeGenerationSupporter.h"\n'
            '#include "ParserEnums.h"\n',
            '\nnamespace tsql::parser {\n\n']
    report, hand_classes, missing = {}, [], []
    for name in used:
        if os.path.exists(os.path.join(hand_dir, name + '.h')):
            hand_classes.append(name)
            continue
        path, text = find_cs_class(ctx.ssd, name)
        if path is None:
            missing.append('%s: C# class not found' % name)
            continue
        rel = os.path.relpath(path, ctx.ssd)
        t = strip_cs_comments(text)
        m = re.search(r'class\s+%s\s*:\s*OptionsHelper<(\w+)>' % name, t)
        if not m:
            missing.append('%s: not an OptionsHelper (%s): create src/parser/helpers/%s.h' % (name, rel, name))
            continue
        enum = m.group(1)
        etype = ('ast::' + enum) if model.enum_kind(enum) == 'ast' else enum
        ctor = re.search(r'(?:private|protected|internal)\s+%s\s*\(\s*\)\s*\{(.*?)\n\s*\}' % name, t, re.S)
        ctor_body = ctor.group(1).replace('this.', '') if ctor else ''
        maps = re.findall(r'AddOptionMapping\(([^;]*)\);', ctor_body)
        body = []
        try:
            for mm in maps:
                args = [cs_arg(x, kwmap, model) for x in re.split(r',(?![^(]*\))', mm)]
                body.append('        AddOptionMapping(%s);\n' % ', '.join(args))
        except ValueError as ex:
            missing.append('%s: %s' % (name, ex))
            continue
        other = re.sub(r'AddOptionMapping\([^;]*\);', '', ctor_body).strip()
        if other:
            missing.append('%s: constructor does more than AddOptionMapping: %r' % (name, other[:80]))
            continue
        # anything besides the constructor and Instance needs a hand port
        rest = t[:ctor.start()] + t[ctor.end():] if ctor else t
        extra = re.findall(r'(?:internal|protected|public|private)\s+(?:static\s+|override\s+|virtual\s+|readonly\s+|const\s+)*[\w<>\.\[\],]+\s+(\w+)\s*(?:\(|=|;)', rest)
        extra = [e for e in extra if e not in (name, 'Instance')]
        hand = os.path.join(hand_dir, name + '.inc')
        if extra and not os.path.exists(hand):
            missing.append('%s has members needing a hand port (%s): create %s' % (name, extra, os.path.relpath(hand, conv_repo())))
            continue
        decl.append('// %s\nclass %s : public OptionsHelper<%s> {\npublic:\n' % (rel, name, etype))
        decl.append('    static const %s& Instance() { static const %s instance; return instance; }\n' % (name, name))
        if extra:
            decl.append('#include "helpers/%s.inc"\n' % name)
        decl.append('    %s() {\n%s    }\n};\n\n' % (name, ''.join(body)))
        report[name] = dict(mappings=len(maps), hand_members=extra)
    decl.append('}  // namespace tsql::parser\n')
    # whole-class hand ports first: generated helpers' hand members may use them
    decl.insert(2, ''.join('#include "helpers/%s.h"\n' % n for n in hand_classes) + '\n')
    write(os.path.join(out, 'OptionHelpers.h'), ''.join(decl))
    return report, hand_classes, missing


def generate(ctx, out):
    """Support code shared by every converted grammar. `ctx`: ssd, model, keyword_sets
    [(grammar_rel, literals)], static_classes and parser_enums (union over all grammars)."""
    rep = {}
    rep['CodeGenerationSupporter_constants'] = gen_cgs(ctx.ssd, out)
    rep['TSqlParserResource_messages'] = gen_resources(ctx.ssd, out)
    nkw, kwmap = gen_keywords(ctx, out)
    # ScriptGeneratorSupporter.GetLowerCase: tokens without a literal get their text from
    # tools/TokenListGenerator's table (punctuation etc.)
    tlg = read_text(os.path.join(ctx.ssd, 'tools/TokenListGenerator/TokenListGenerator.cs'))
    for k, v in re.findall(r'_map\.Add\("(\w+)",\s*"((?:[^"\\]|\\.)*)"\)', tlg):
        kwmap.setdefault(k, v)
    rep['keywords'] = nkw
    hand_dir = os.path.join(conv_repo(), 'src/parser/helpers')
    rep['option_helpers'], rep['hand_classes'], rep['helper_issues'] = gen_helpers(ctx, kwmap, out, hand_dir)
    # enums the hand-ported helper classes use (Enum.TryParse<T> etc.)
    helper_enums = set()
    for f in sorted(os.listdir(hand_dir)):
        for w in set(re.findall(r'\b[A-Z]\w+\b', read_text(os.path.join(hand_dir, f)))):
            if ctx.model.enum_kind(w) == 'parser':
                helper_enums.add(w)
    rep['parser_enums'] = gen_parser_enums(ctx.model, set(ctx.parser_enums) | helper_enums, out)
    return rep


def conv_repo():
    return os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
